sudo: required
language: cpp

os:
  - linux

compiler:
  - g++
  
env:
  global:
    - CODECOV_TOKEN='b233dcfd-60f5-4f1e-a30f-846ec3f3a3f6'

script:
  - sudo apt update
  - sudo apt install valgrind
  - sudo apt install cppcheck
  - sudo apt-get install lcov
  
  - git clone https://github.com/google/googletest.git -b release-1.11.0
  - cd googletest
  - mkdir build
  - cd build
  - cmake .. -DBUILD_GMOCK=OFF
  - cd ../..
  
  - cmake ./CMakeLists.txt
  - make
  - ls
  - ./tests
  
  - valgrind ./tests
  - cppcheck --inconclusive --enable=all --language=c ./shapes.c ./main.c
  
after_success:
  - bash <(curl -s https://codecov.io/bash)  
  - lcov —capture —directory . —output-file coverage.info
