sudo: required

language: cpp

os:
  - linux

compiler:
  - g++

script:
  - sudo apt update
  - sudo apt install valgrind
  - sudo apt install cppcheck
  
  - git clone https://github.com/google/googletest.git -b release-1.11.0
  - cd googletest
  - mkdir build
  - cd build
  - cmake .. -DBUILD_GMOCK=OFF
  - make
  - sudo make install
  - cd ../..
  - cmake ./CMakeLists.txt
  - make
  - ls
  - ./tests
  - valgrind ./tests
  - cppcheck --inconclusive --enable=all --language=c ./shapes.c ./main.c
