sudo: required
language: cpp

os:
  - linux

compiler:
  - g++
  
env:
  global:
    - CODECOV_TOKEN='b233dcfd-60f5-4f1e-a30f-846ec3f3a3f6'
    
install:
  - sudo apt update
  - sudo apt install valgrind
  - sudo apt install cppcheck
  - sudo apt-get install lcov
  # Google tests
  - sudo apt-get install libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake .
  - sudo make
  - sudo cp *.a /usr/lib

script:   
  - cmake ./CMakeLists.txt
  - make
  - ls
  - ./tests
  
  - valgrind ./tests
  - cppcheck --inconclusive --enable=all --language=c ./shapes.c ./main.c
  
after_success:
  - lcov --capture --directory . --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info
